language: php
php:
  - 7.2
before_script:
  - composer self-update
  - composer update
  - composer install --prefer-source --no-interaction --dev
script:
  - vendor/bin/phpunit
notifications:
  email: thiodor@gmail.com
